export const UPDATE_VALUE = 'UPDATE_VALUE';
export const INSERT_LIST_ITEM = 'INSERT_LIST_ITEM';
export const DELETE_LIST_ITEM = 'DELETE_LIST_ITEM';
export const UPDATE_LIST_ITEM = 'UPDATE_LIST_ITEM';
export const UPDATE_LIST_ITEM_FIELD = 'UPDATE_LIST_ITEM_FIELD';
